// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterFile(arg1) {
  return window['go']['main']['App']['FilterFile'](arg1);
}

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SetOptions(arg1) {
  return window['go']['main']['App']['SetOptions'](arg1);
}

export function SplitFilePath(arg1) {
  return window['go']['main']['App']['SplitFilePath'](arg1);
}
