// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FilterFile(arg1:string):Promise<string>;

export function GetOptions():Promise<main.Options>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetOptions(arg1:main.Options):void;

export function SplitFilePath(arg1:string):Promise<main.PathStruct>;
